# Generated by Django 5.1.4 on 2025-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=10)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('parking_slot', models.CharField(max_length=10)),
            ],
        ),
    ]
